spring:
  datasource:
    # Use the 'jdbc' prefix and ensure sslmode=require is present
    url: ${DB_URL}
    username: ${DB_USERNAME} # Use env variables for security
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Flyway handles the schema, Hibernate only validates

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cloudinary:
    resume-url: ${CLOUDINARY_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # Limit exposure for security
  endpoint:
    health:
      show-details: when_authorized # Hide DB details from public
      probes:
        enabled: true # Enables Liveness and Readiness probes
  info:
    env:
      enabled: true