spring:
  datasource:
    # Use the 'jdbc' prefix and ensure sslmode=require is present
    url: ${DB_URL}
    username: ${DB_USERNAME} # Use env variables for security
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Flyway handles the schema, Hibernate only validates

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MY_EMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

app:
  cloudinary:
    resume-url: ${CLOUDINARY_URL}
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus # Added Prometheus for scraping
  endpoint:
    health:
      show-details: when-authorized # Shows DB and Cloudinary status in the JSON response
      probes:
        enabled: true # Vital for Render's zero-downtime deployment
  health:
    db:
      enabled: true
    mail:
      enabled: true
  metrics:
    tags:
      application: portfolio-backend
  info:
    env:
      enabled: true