CREATE TABLE profile (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         headline VARCHAR(255) NOT NULL,
                         sub_headline TEXT,
                         resume_url VARCHAR(500),
                         created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed your initial data (The text from your screenshot)
INSERT INTO profile (name, headline, sub_headline, resume_url)
VALUES (
           'Ajay Nair',
           'Transforming Ideas Into Scalable Architecture',
           'Full Stack Developer with 2.5+ years of experience bridging the gap between complex backend logic and intuitive user interfaces. Experienced in modernizing enterprise systems for stability and speed.',
           'https://your-storage-link.com/resume.pdf'
       );