-- For the left-side text
CREATE TABLE work_section (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              title VARCHAR(255) DEFAULT 'Featured Engineering',
                              description TEXT
);

-- Main Project Table
CREATE TABLE projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      thumbnail_path VARCHAR(255),
      description TEXT,
      display_order INT
);

-- Project Tech Stack (Simple String List)
CREATE TABLE project_tech_stack (
    project_id BIGINT REFERENCES projects(id),
    tech_name VARCHAR(50) -- Stores icon names like 'SiNextdotjs'
);

-- Project Links (CTA)
CREATE TABLE project_links (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   project_id BIGINT REFERENCES projects(id),
   label VARCHAR(50), -- "View Code"
   icon_name VARCHAR(50), -- "FaGithub"
   url VARCHAR(255)
);