-- Left Section: Bio and Counters
CREATE TABLE IF NOT EXISTS about_section (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title VARCHAR(255) DEFAULT 'Robust architecture drives scalable systems.',
   description TEXT,
   years_experience VARCHAR(10) DEFAULT '2.5 +',
   projects_completed VARCHAR(10) DEFAULT '10 +',
   tech_debt_reduced VARCHAR(10) DEFAULT '40 %'
);

-- Skills Tab: Categories (e.g., Frontend & UI)
CREATE TABLE IF NOT EXISTS  skill_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL
);

-- Skills Tab: Individual Icons
CREATE TABLE IF NOT EXISTS  skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES skill_categories(id),
    skill_name VARCHAR(100) NOT NULL,
    icon_name VARCHAR(100) NOT NULL -- e.g., 'FaReact'
);

-- Awards Table
CREATE TABLE IF NOT EXISTS  awards (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        stage VARCHAR(100), -- e.g., "2021 - 2022"
                        description TEXT
);

-- Experience Table
CREATE TABLE IF NOT EXISTS  experience (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(255) NOT NULL,
                            stage VARCHAR(100), -- e.g., "July 2023 - Present"
                            description TEXT
);

-- Certifications/Education Table
CREATE TABLE IF NOT EXISTS  certifications (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                title VARCHAR(255) NOT NULL,
                                stage VARCHAR(100), -- e.g., "University of Mumbai"
                                description TEXT
);

-- Initial Seed Data
INSERT INTO about_section (description) VALUES ('Over the past 2.5+ years, my focus has been on engineering enterprise-grade solutions. At ISS-STOXX, I specialize in modernizing legacy architectures...');

INSERT INTO skill_categories (category_name) VALUES ('Frontend & UI'), ('Backend & APIs'), ('Data & Cloud');

INSERT INTO skills (category_id, skill_name, icon_name) VALUES
                                                            (1, 'JavaScript', 'FaJs'), (1, 'React', 'FaReact'), (1, 'Next.js', 'SiNextdotjs'),
                                                            (2, 'Java', 'FaJava'), (2, 'Spring Boot', 'SiSpringboot'), (2, 'Python', 'FaPython'),
                                                            (3, 'MySQL', 'SiMysql'), (3, 'MongoDB', 'SiMongodb'), (3, 'Azure', 'SiMicrosoftazure');


-- Seed Data for Experience (Extracted from your SS)
INSERT INTO experience (title, stage, description)
VALUES ('Full Stack Software Developer | ISS-STOXX', 'July 2023 - Present', 'Engineered the modernization of legacy Spring Boot and React architectures for enterprise climate applications. Optimized data ingestion pipelines for large-scale Parquet datasets, improving processing efficiency by 40%...');

-- Seed Data for Awards
INSERT INTO awards (title, stage, description)
VALUES ('Microsoft AI for Earth Grant ($15,000 USD)', '2021 - 2022', 'Awarded for an AI-based statistical analysis project on land-use plastic pollution.'),
       ('Deep Blue Hackathon Winner - 1st Place', '2023', 'Created a minutes of meeting generator inside MS Teams.');

INSERT INTO certifications (title, stage, description) VALUES
                                                           ('B.E. Computer Engineering', 'University of Mumbai', 'Secured a First Class with Distinction, graduating in 2023 with a CGPA of 9.7/10.0...'),
                                                           ('Machine Learning Specialization', 'Coursera (Andrew Ng)', 'Covered supervised learning, unsupervised learning, and best practices in machine learning.');