CREATE TABLE contact_messages (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(100) NOT NULL,
                                  email VARCHAR(150) NOT NULL,
                                  subject VARCHAR(200),
                                  message TEXT NOT NULL,
                                  ip_address VARCHAR(45),
                                  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);