CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(50) NOT NULL
);

-- Seed admin user (Password is 'admin123' hashed with BCrypt)
INSERT INTO users (email, password, role)
VALUES ('spamvinup@gmail.com', '$2a$10$8.07Z9v850VXL0yZdzK95.8M5t/6L9Yy3tX3yE.pD1r3r3r3r3r3r', 'ROLE_ADMIN');