name: Keep Alive
on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            curl -i -m 10 https://portfolio-backend-fsqx.onrender.com/actuator/health && break
            if [ $i -lt 3 ]; then sleep 5; fi
          done
